yolo_model:

  config_file:
    name: yolo-obj.cfg
  weight_file:
    name: yolo-obj_best.weights
  threshold:
    value: 0.5
  detection_classes:
    names:
      - banana
      - camera_sign
      - yellow_duck
      - helmet
      - lego_child
      - pineapple
      - rope
      - stop_sign
    
